# Generated by Django 4.2.5 on 2023-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.FloatField(blank=True, default=float("nan"), null=True),
        ),
    ]
